name: CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build (${{ matrix.os }}/${{ matrix.arch }})
    runs-on: ubuntu-latest

  env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            ext: ""

          - os: windows
            arch: amd64
            ext: ".exe"

          - os: darwin
            arch: amd64
            ext: ""

    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v4


      - name: ⚙️ Configurar ambiente Go
        uses: actions/setup-go@v5
        with:
          go-version-file: apps/cli-assinador/go.mod
          cache: true
          cache-dependency-path: apps/cli-assinador/go.sum


      - name: 🧪 Executar testes unitários
        working-directory: apps/cli-assinador
        run: |
          go test ./tests/... -v


      - name: 🔎 Análise estática (go vet)
        working-directory: apps/cli-assinador
        run: |
          go vet ./...


      - name: 🔨 Compilar CLI Assinador
        working-directory: apps/cli-assinador
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: "0"
        run: |
          mkdir -p ../../dist

          go build \
            -ldflags="-s -w -X main.versaoApp=${GITHUB_SHA::8}" \
            -o ../../dist/assinatura-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }} \
            .


      - name: 📦 Publicar artefato gerado
        uses: actions/upload-artifact@v4
        with:
          name: assinatura-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/assinatura-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
          if-no-files-found: error
